apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-graphite.fullname" . }}
  labels:
    app: {{ include "grafana-graphite.name" . }}
    chart: {{ include "grafana-graphite.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name | quote }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
  {{- end }}
  selector:
    app: {{ include "grafana-graphite.name" . }}
    release: {{ .Release.Name }}
