# Default values for grafana-graphite.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: aaronjamesford/grafana-graphite
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: grafana-graphite
  type: ClusterIP
  ports:
    - name: grafana-web
      port: 80
      protocol: TCP
    - name: graphite-web
      port: 81
      protocol: TCP
    - name: statsd-c
      port: 8125
      protocol: UDP
    - name: statsd-m
      port: 8126
      protocol: TCP
    - name: graphite-carbon
      port: 2003
      protocol: TCP

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 0.1
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
